# Generated by Django 4.1.7 on 2023-07-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending request"),
                    ("Accepted", "Accepted request"),
                    ("Rejected", "Rejected request"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
