# Generated by Django 4.1.7 on 2023-07-31 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0002_alter_connectionrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrimonialprofileimage",
            name="image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FavouriteProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matrimonials.matrimonialprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_profiles",
                        to="matrimonials.matrimonialprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
