# Generated by Django 4.1.7 on 2023-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0003_alter_matrimonialprofileimage_image_favouriteprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="education",
            field=models.CharField(
                choices=[
                    ("Under Graduation", "Under Graduation"),
                    ("Graduation", "Graduation"),
                    ("Post Graduation", "Post Graduation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                    ("Hindu", "Hindu"),
                    ("Sikh", "Sikh"),
                    ("Buddhism", "Buddhism"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
