# Generated by Django 4.1.7 on 2023-08-02 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0004_alter_matrimonialprofile_education_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matrimonialprofile",
            name="birthday",
        ),
    ]
