# Generated by Django 4.1.7 on 2023-08-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0005_remove_matrimonialprofile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="country",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
