# Generated by Django 4.1.7 on 2023-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0006_alter_matrimonialprofile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="income",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
