# Generated by Django 4.1.7 on 2023-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0007_alter_matrimonialprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="income",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
