# Generated by Django 4.1.7 on 2023-09-03 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0009_alter_matrimonialprofileimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="conversation_id",
            new_name="conversation",
        ),
    ]
