# Generated by Django 4.1.7 on 2023-07-29 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="text",
            new_name="comment",
        ),
    ]
