# Generated by Django 4.1.7 on 2023-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_text_feedback_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(
                blank=True, help_text="The avatar image of the user.", max_length=255
            ),
        ),
    ]
