# Generated by Django 4.1.7 on 2023-07-29 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_chat_message_adreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="chat_id",
            new_name="chat",
        ),
    ]
