# Generated by Django 4.1.7 on 2023-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_rename_chat_id_message_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcategory",
            name="image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adimage",
            name="image",
            field=models.URLField(),
        ),
    ]
