# Generated by Django 4.1.7 on 2023-08-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0006_alter_ad_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="ads.adsubcategory",
            ),
        ),
    ]
