# Generated by Django 4.1.7 on 2023-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0007_ad_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
