# Generated by Django 4.1.7 on 2023-08-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0008_alter_ad_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="adreport",
            name="ad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_reports",
                to="ads.ad",
            ),
            preserve_default=False,
        ),
    ]
