# Generated by Django 4.1.7 on 2023-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0009_adreport_ad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={},
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["is_approved", "status"], name="ads_ad_is_appr_b74706_idx"
            ),
        ),
    ]
